# Site settings
title: Jekyll-materialize
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
url: "http://yourdomain.com"
baseurl: ""
logo: jekyll-<b>materialize</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: ichihara.rifa@gmail.com
    facebook:
        show: true
        name: "Ichihara Rifa"
        url: "https://fb.me/nasya.aidan"
    github:
        show: true
        username: "riefachan"
    twitter:
        show: false
        username: ""
    disqus:
        show: true
        username: "ichihararifa"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-feed